name: StartServerTest

on:
  repository_dispatch:
    types: ServerStart
  workflow_dispatch:
    
jobs:
  StartServer:
    runs-on: ubuntu-latest
    name: EmbyServer
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Emby Install
        run: |
          sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable
          sudo apt install qbittorrent-nox
          sudo adduser --system --group qbittorrent-nox
          sudo adduser runner qbittorrent-nox
          sudo wget https://github.com/MediaBrowser/Emby.Releases/releases/download/4.5.4.0/emby-server-deb_4.5.4.0_amd64.deb
          sudo dpkg -i emby-server-deb_4.5.4.0_amd64.deb
          sudo apt install nodejs
          sudo qbittorrent-nox --daemon --webui-port=8081
          wget https://github.com/embygithub/jellyfin/blob/master/cloudflared-stable-linux-amd64.deb
          sudo dpkg -i cloudflared-stable-linux-amd64.deb
          cd ~/
          mkdir .cloudflared
          cd .cloudflared
          cat << EOF >> cert.pem
          ${{ secrets.CF_CERT }}
          EOF
          cloudflared --url localhost:8096 --hostname embygit.arihant.ga & cloudflared --url localhost:8081 --hostname torrentgit.arihant.ga   
        
